Support for RHEL driver disk v3
Starting with RHEL6 there will be a new driver disk format. In the
new format, driver disk will contain RPMs instead of module.cgz files.
These RPMs are very similar to Novell's KMPs and are picked up by
Anaconda during the installation given they provide
"kernel-modules = <running kernel version>".

Signed-off-by: prudhvi_tella <prudhvi_tella@localhost.localdomain>

diff --git a/dkms b/dkms
--- a/dkms
+++ b/dkms
@@ -1969,11 +1969,15 @@ make_redhat_driver_disk()
 	    fi
 	done
     fi
-
-    if [[ ($distro = redhat2 || $multi_arch = true) && ! $redhat1_okay ]]; then
+    if [ "$distro" == "redhat2" ]  && [ -z "$redhat1_okay" ]; then
 	echo $"Creating Red Hat v2 driver disk (arch support)."
 	echo $""
 	local rhdd_filename="rhdd"
+    elif [ "$distro" == "redhat3" ] && [ -z "$redhat1_okay" ]; then
+        echo $"Creating Red Hat v3 driver disk."
+	echo $""
+	make_redhat3_driver_disk
+	return
     else
 	echo $"Creating Red Hat v1 driver disk."
 	echo $""
@@ -2095,9 +2099,9 @@ make_driver_disk()
 
     # Confirm that distro is supported
     case $distro in
-	redhat | redhat[12] | suse | UnitedLinux | ubuntu) ;;
+	redhat | redhat[123] | suse | UnitedLinux | ubuntu) ;;
 	*) die 3 $"Invalid distro argument. Currently, the distros" \
-		$"supported are: redhat, redhat1, redhat2, suse, UnitedLinux" \
+		$"supported are: redhat, redhat1, redhat2, redhat3, suse, UnitedLinux" \
 		$"               ubuntu";;
     esac
 
@@ -3124,6 +3128,126 @@ autoinstall() {
 	(module="$m"; module_version="$v"; install_module) &
     done
     wait
+}
+
+function make_redhat3_driver_disk ()
+{
+    # Check that the rpmbuild command is present
+    if ! which rpmbuild >/dev/null 2>&1 ; then
+        echo $"" >&2
+        echo $"Error! rpmbuild not present." >&2
+        echo $"Install the rpm-build package." >&2
+        exit 1
+    fi
+
+    local kmodtool=$(rpm -ql redhat-rpm-config | grep kmodtool)
+    #Check that the kmodtool is present
+    if [ -z "$kmodtool" ]; then
+        echo $"Error! kmodtool not present." >&2
+        echo $"Install redhat-rpm-config package." >&2
+        exit 1
+    fi
+
+    echo $""
+    if [ -n "$specfile" -a -e "$dkms_tree/$module/$module_version/source/$specfile" ]; then
+        echo $"Using $dkms_tree/$module/$module_version/source/$specfile"
+        SPECFILE="$dkms_tree/$module/$module_version/source/$specfile"
+    elif [ -e "/etc/dkms/template-dkms-redhat-kmod.spec" ]; then
+        echo $"Using /etc/dkms/template-dkms-redhat-kmod.spec"
+        SPECFILE="/etc/dkms/template-dkms-redhat-kmod.spec"
+    else
+        echo $"" >&2
+        echo $"Cannot find /etc/dkms/template-dkms-redhat-kmod.spec which is needed by" >&2
+        echo $"DKMS in order to make Redhat driver disk v3." >&2
+        exit 5
+    fi
+    # Set up temporary build directory for build
+    rm -rf "$dkms_tree/$module/$module_version/build"
+    cp -rf "$dkms_tree/$module/$module_version/source/" "$dkms_tree/$module/$module_version/build"
+
+    # Run the pre_build script
+    if [ -n "$pre_build" ] && [ -x `echo "$dkms_tree/$module/$module_version/source/$pre_build" | sed 's/ .*//'` ]; then
+        echo $""
+        echo $"Running the pre_build script:"
+        $dkms_tree/$module/$module_version/source/$pre_build
+    fi
+
+    cd "$dkms_tree/$module/$module_version/build"
+
+    # Apply any patches
+    local index=0
+    while [ $index -lt ${#patch_array[@]} ]; do
+        if ! [ -e "$dkms_tree/$module/$module_version/build/patches/${patch_array[$index]}" ]; then
+            echo $"" >&2
+            echo $"Error!  Patch ${patch_array[$index]} as specified in dkms.conf cannot be" >&2
+            echo $"found in $dkms_tree/$module/$module_version/build/patches/." >&2
+            exit 5
+        fi
+        invoke_command "patch -p1 < ./patches/${patch_array[$index]}" "applying patch ${patch_array[$index]}"
+        if [ "$?" -ne 0 ]; then
+            echo $"" >&2
+            echo $"Error! Application of patch ${patch_array[$index]} failed." >&2
+            echo $"Check $dkms_tree/$module/$module_version/build/ for more information." >&2
+                report_build_problem
+            exit 6
+        fi
+        index=$(($index+1))
+    done
+    # Create temp dirs and copy files for build
+    local temp_dir_name=`mktemp -d $tmp_location/dkms.XXXXXX`
+    trap 'rm -rf $temp_dir_name' EXIT HUP TERM
+    mkdir -p ${temp_dir_name}/{disk,BUILD,RPMS,SRPMS,SPECS,SOURCES}
+    cp ${SPECFILE} ${temp_dir_name}/SPECS/$module.spec
+    cp -rax $dkms_tree/$module/$module_version/build/ $temp_dir_name/SOURCES/$module-$module_version/
+    # Clean the build directory
+    rm -rf "$dkms_tree/$module/$module_version/build/*"
+    cd $temp_dir_name/SOURCES
+    invoke_command "tar -jcvf $temp_dir_name/SOURCES/$module-$module_version.tar.bz2 $module-$module_version/" "creating source tarball"
+    local i=0
+    #Build RPMS
+    while [ $i -lt ${#kernelver_array[@]} ]; do
+        invoke_command "LC_ALL=C rpmbuild --define \"_topdir ${temp_dir_name}\" --define \"version $module_version\" --define \"module_name $module\" --define \"kernel_version ${kernelver_array[$i]}\" -bb --target ${arch_array[$i]} ${temp_dir_name}/SPECS/$module.spec > ${temp_dir_name}/rpmbuild.log 2>&1" "rpmbuild"
+        if [ "$?" -ne 0 ]; then
+            echo $"" >&2
+            echo $"Error! There was a problem creating your kmod." >&2
+            cat ${temp_dir_name}/rpmbuild.log >&2
+            exit 7
+        fi    
+        i=$(($i + 1))
+    done
+
+    i=0
+    while [ $i -lt ${#arch_array[@]} ]; do
+        invoke_command "createrepo --pretty ${temp_dir_name}/RPMS/${arch_array[$i]}" "creating repo"
+        if [ "$?" -ne 0 ]; then
+            echo $"" >&2
+            echo $"Error! There was a problem creating repository." >&2
+            exit 7
+        fi
+        i=$(($i + 1))
+    done
+
+    echo "$module-$module_version driver disk" > "${temp_dir_name}/disk/rhdd3"
+    mkdir ${temp_dir_name}/disk/rpms
+    cp -rax ${temp_dir_name}/RPMS/* ${temp_dir_name}/disk/rpms/
+
+    local suffix="$(driver_disk_suffix)"
+    local image_dir="$dkms_tree/$module/$module_version/driver_disk"
+    local image_name="$module-$module_version-dd.$suffix"
+    echo $""
+    echo $"Creating driver disk on $media media:"
+    cd "${temp_dir_name}/disk"
+    mkdir -p "$image_dir"
+    rm -f "$image_dir/$image_name"
+    make_driver_disk_media "$image_dir/$image_name" "${temp_dir_name}/disk"
+    rm -rf $temp_dir_name
+
+    echo $""
+    echo $"Disk image location: $image_dir/$image_name"
+    echo $""
+    echo $"DKMS: mkdriverdisk Completed."
+    
+    trap > /dev/null 2>&1
 }
 
 #############################
