Ensure users are alerted to kernel module signing failures

diff --git a/dkms.in b/dkms.in
--- a/dkms.in
+++ b/dkms.in
@@ -1325,7 +1325,10 @@ prepare_and_actual_build()
 
         if (( do_signing )); then
             echo "Signing module $built_module"
-            "$sign_file" "$sign_hash" "$mok_signing_key" "$mok_certificate" "$built_module" 2>/dev/null
+            if ! signing_command_output=$("$sign_file" "$sign_hash" "$mok_signing_key" "$mok_certificate" "$built_module" 2>&1); then
+                echo "ERROR: Failed to sign module '$built_module'!"
+                echo "$signing_command_output"
+            fi
         fi
 
         if [[ $module_compressed_suffix = .gz ]]; then
