do not run depmod if modules.dep does not yet exist
i.e. only linux headers but no corresponding linux image is installed

diff --git a/dkms.in b/dkms.in
--- a/dkms.in
+++ b/dkms.in
@@ -337,6 +337,12 @@ do_depmod()
     if [[ ${current_os} != Linux ]] ; then
         return
     fi
+    if [[ ! -f $install_tree/$1/modules.dep ]]; then
+        # if the corresponding linux image $1 is not installed
+        # do not create modules.dep
+        echo "Skipping depmod because '$install_tree/$1/modules.dep' is missing."
+        return
+    fi
     if [[ -f /boot/System.map-$1 ]]; then
         depmod -a "$1" -F "/boot/System.map-$1"
     else
@@ -347,7 +353,7 @@ do_depmod()
         # no longer installed kernel $1, so do not leave stale depmod files around
         rm -fv $install_tree/$1/modules.{alias,dep,devname,softdep,symbols,*.bin}
         rmdir --ignore-fail-on-non-empty $install_tree/$1
-        [[ -d $install_tree/$1 ]] || echo $"Removed $install_tree/$1"
+        [[ -d $install_tree/$1 ]] || echo $"removed directory $install_tree/$1"
     fi
 }
 
