dkms.in: exit if cd fails
Signed-off-by: Nowa Ammerlaan <nowa@gentoo.org>

diff --git a/dkms.in b/dkms.in
--- a/dkms.in
+++ b/dkms.in
@@ -73,6 +73,7 @@
 # 12: setup_kernels_arches(): Could not determine architecture.
 # 13: build: Aborting build of module ... for kernel ... due to missing BUILD_DEPENDS: ...
 # 14: kernel_preinst/prerm: dkms kernel_preinst/prerm for kernel ... failed for module(s) ...
+# 15: gloabl: a call to cd failed
 # 21: prepare_kernel(): Your kernel headers for kernel ... cannot be found ...
 # 77: skipped due to BUILD_EXCLUSIVE
 # 101: install: pre_install failed, aborting install.
@@ -976,7 +977,7 @@ run_build_script() {
         else
         echo "Running the $1 script:"
         (
-            cd "$dkms_tree/$module/$module_version/$script_type/"
+            cd "$dkms_tree/$module/$module_version/$script_type/" || exit 15
             exec $run
         )
         fi
@@ -1223,7 +1224,7 @@ prepare_and_actual_build()
     echo "DKMS (@RELEASE_STRING@) make.log for $module/$module_version for kernel $kernelver ($arch)" >> "$build_log"
     date >> "$build_log"
 
-    cd "$build_dir"
+    cd "$build_dir" || exit 15
 
     # Apply any patches
     for p in "${patch_array[@]}"; do
@@ -1298,7 +1299,7 @@ prepare_and_actual_build()
             "Make sure the name of the generated module is correct and at the root of the" \
             "build directory, or consult $build_log for more information."
     done
-    cd - >/dev/null
+    cd - >/dev/null || exit 15
 
     # Build success, so create DKMS structure for a built module
     mkdir -p "$base_dir/log"
@@ -1346,10 +1347,10 @@ prepare_and_actual_build()
     run_build_script post_build "$post_build" "$build_log"
 
     # Run the clean commands
-    cd "$dkms_tree/$module/$module_version/build"
+    cd "$dkms_tree/$module/$module_version/build" || exit 15
     invoke_command "$clean" "Cleaning build area" "$build_log" background
 
-    cd - >/dev/null
+    cd - >/dev/null || exit 15
 
     # Save the log file
     mv -f "$build_log" "$base_dir/log/make.log" 2>/dev/null
