dkms: always check for perm during make_tarball
Currently we check for write permissions only if --archive is provided
and is pointing to an existing folder.

In any other case we don't bother, so we get cryptic error messages.

Signed-off-by: Emil Velikov <emil.l.velikov@gmail.com>

diff --git a/dkms.in b/dkms.in
--- a/dkms.in
+++ b/dkms.in
@@ -1701,22 +1701,23 @@ make_tarball()
     local tarball_name="$module-$module_version-$kernel_version_list.dkms.tar.gz"
     local tarball_dest="$dkms_tree/$module/$module_version/tarball/"
 
-    # Die if we will not be able to create the tarball due to permissions.
     if [[ $archive_location ]]; then
         tarball_name="${archive_location##*/}"
-        if [[ ${archive_location%/*} != $archive_location && \
-            -d ${archive_location%/*} && -w ${archive_location%/*} ]]; then
+        if [[ ${archive_location%/*} != $archive_location ]]; then
             tarball_dest="${archive_location%/*}"
-        elif [[ ${archive_location%/*} != $archive_location ]] && ! mkdir -p $tarball_dest; then
-            die 9 $"Will not be able to create $archive_location due to a permissions problem."
         fi
-    fi
-    if [ ! -d $tarball_dest ]; then
-        mkdir -p "$dkms_tree/$module/$module_version/tarball/"
     fi
 
     echo $""
     echo $"Tarball location: $tarball_dest/$tarball_name"
+
+    if [[ ! -d $tarball_dest ]]; then
+        if ! mkdir -p "$tarball_dest" 2>/dev/null; then
+            die 9 $"Missing write permissions for $tarball_dest."
+        fi
+    fi
+
+    [[ -w $tarball_dest ]] || die 9 $"Missing write permissions for $tarball_dest."
 
     if ! tar -C $temp_dir_name -caf $tarball_dest/$tarball_name . 2>/dev/null; then
         die 6 $"Failed to make tarball."
