Add 07-exit-if-build-fails.patch from Debian to show proper error messages

diff --git a/dkms b/dkms
--- a/dkms
+++ b/dkms
@@ -3241,10 +3241,27 @@ function make_debian()
     case "$create_type" in
         dsc)
             invoke_command "dpkg-buildpackage -S -us -uc 1>/dev/null" "Building source package"
+	    if [ "$?" -eq 0 ]; then
+		    echo $""
+		    echo $"DKMS: mk${create_type} Completed."
+	    else
+		    echo $"" >&2
+		    echo $"Error! There was a problem creating your ${create_type}." >&2
+		    exit 7
+	    fi
             invoke_command "mv '$temp_dir/${debian_package}-dkms_${module_version}.dsc' '$temp_dir/${debian_package}-dkms_${module_version}.tar.gz' '$deb_basedir'" "Moving built files to $deb_basedir"
             ;;
         deb)
             invoke_command "dpkg-buildpackage -rfakeroot -b -us -uc 1>/dev/null" "Building binary package"
+            if [ "$?" -eq 0 ]; then
+		    echo $""
+		    echo $"DKMS: mk${create_type} Completed."
+	    else
+		    echo $"" >&2
+		    echo $"Error! There was a problem creating your ${create_type}." >&2
+		    exit 7
+	    fi
+
             invoke_command "mv '$temp_dir/${debian_package}-dkms_${module_version}_all.deb' '$deb_basedir'" "Moving built files to $deb_basedir"
             ;;
     esac
@@ -3260,12 +3277,9 @@ function make_debian()
     delete_temporary_trees
 
     #done
-    if [ "$?" -eq 0 ]; then
-        echo $""
-        echo $"DKMS: mk${create_type} Completed."
-    else
+    if [ "$?" -ne 0 ]; then
         echo $"" >&2
-        echo $"Error! There was a problem creating your ${create_type}." >&2
+	echo $"Error! There was a problem cleaning up temporary files." >&2
         exit 7
     fi
 }
