dkms: skip module signing when hash is unknown
Currently we'll attempt to sign the modules, even when we don't have the
kernel config and/or when CONFIG_MODULE_SIG_HASH is not set.

This serves little purpose, since in either of those cases the kernel
won't check the signature.

Surprise! Turns out Debian 9 does not enable signing, even though it
ships the sign-file tool.

Signed-off-by: Emil Velikov <emil.l.velikov@gmail.com>

diff --git a/dkms.in b/dkms.in
--- a/dkms.in
+++ b/dkms.in
@@ -905,13 +905,17 @@ prepare_signing()
 {
     do_signing=0
 
-    if [[ -f "${kernel_config}" ]]; then
-        sign_hash="$(grep "^CONFIG_MODULE_SIG_HASH=" "${kernel_config}" | sed 's/CONFIG_MODULE_SIG_HASH=//;s/"//g')"
-        # The kernel may be built without module signing facility. CONFIG_MODULE_SIG_HASH is unset in kconfig
-        sign_hash="${sign_hash:-sha512}"
-    else
-        sign_hash="sha512"
+    if [[ ! -f "${kernel_config}" ]]; then
+        echo "Kernel config ${kernel_config} not found, modules won't be signed"
+        return
     fi
+
+    if ! grep -q "^CONFIG_MODULE_SIG_HASH=" "${kernel_config}"; then
+        echo "The kernel is be built without module signing facility, modules won't be signed"
+        return
+    fi
+
+    sign_hash=$(grep "^CONFIG_MODULE_SIG_HASH=" "${kernel_config}" | cut -f2 -d= | sed 's/"//g')
 
     # Lazy source in signing related configuration
     read_framework_conf $dkms_framework_signing_variables
