dkms: do_install: simplify the actual copying part

diff --git a/dkms.in b/dkms.in
--- a/dkms.in
+++ b/dkms.in
@@ -1633,11 +1633,15 @@ do_install()
         fi
 
         # Copy module to its location
-        echo "Installing $install_tree/$kernelver${dest_module_location[$count]}/${dest_module_name[$count]}$module_suffix"
-        mkdir -p "$install_tree/$kernelver${dest_module_location[$count]}"
         local toinstall
+        local dest_dir
+        local dest_name
         toinstall=$(compressed_or_uncompressed "$base_dir/module" "$m")
-        cp -f $symlink "$toinstall" "$install_tree/$kernelver${dest_module_location[$count]}/${toinstall##*/}" || die 6 "Copying '$toinstall' failed"
+        dest_dir="$install_tree/$kernelver${dest_module_location[$count]}"
+        dest_name=${toinstall##*/}
+        echo "Installing $dest_dir/$dest_name"
+        mkdir -p "$dest_dir"
+        cp -f $symlink "$toinstall" "$dest_dir/$dest_name" || die 6 "Copying '$toinstall' failed"
         any_module_installed=1
 
     done
