Don't log all information to /dev/console (which would spam vt1), but instead to /var/log/dkms_autoinstaller.  Also, if you are on Debian/Ubuntu where some nice init style scripts are available, use them

diff --git a/dkms_autoinstaller b/dkms_autoinstaller
--- a/dkms_autoinstaller
+++ b/dkms_autoinstaller
@@ -15,32 +15,38 @@
 # Description: A service to automatically install DKMS modules for new kernels.
 ### END INIT INFO
 
+#use LSB functions for logging on Debian/Ubuntu
+if [ -f /lib/lsb/init-functions ]; then
+    . /lib/lsb/init-functions
+    DEBIAN_STYLE_LOGGING="yes"
+fi
+
 test -f /usr/sbin/dkms || exit 0
 
 function invoke_command ()
 {
     local exitval=0
     local exitval_file=`mktemp /tmp/dkms.XXXXXX`
-    [ -z "$verbose" ] && echo -en "$2..." >$output_loc || echo -e "$1" >$output_loc
+    [ -z "$verbose" ] && echo -en "$2..." >>$output_loc || echo -e "$1" >>$output_loc
     if [ "$3" == background ] && [ -z "$verbose" ]; then
 	(eval $1 >/dev/null 2>&1; echo "exitval=$?" >> "$exitval_file") &
 	while [ -e "$exitval_file" ] && ! [ -s "$exitval_file" ]; do
 	    sleep 3
-	    echo -en "." >$output_loc
+	    echo -en "." >>$output_loc
 	done
 	. "$exitval_file"
     else
 	eval $1; exitval=$?
     fi
-    [ $exitval -gt 0 ] && echo -en "(bad exit status: $exitval)" >$output_loc
+    [ $exitval -gt 0 ] && echo -en "(bad exit status: $exitval)" >>$output_loc
     rm -f "$exitval_file"
-    echo -en "\n" >$output_loc
+    echo -en "\n" >>$output_loc
     return $exitval
 }
 
 
 # Set Variables
-output_loc="/dev/console"
+output_loc="/var/log/dkms_autoinstaller"
 [ -n "$2" ] && kernel=$2 && output_loc="/dev/stdout" || kernel=`uname -r`
 kernelver_rpm=`rpm -qf "/lib/modules/$kernel" 2>/dev/null | grep -v "not owned by any package" | grep kernel | head -1`
 if ! arch=`rpm -q --queryformat "%{ARCH}" "$kernelver_rpm" 2>/dev/null`; then
@@ -53,7 +59,12 @@ dkms_tree="/var/lib/dkms"
 # See how we were called.
 case "$1" in
   start)
-	echo "" >$output_loc
+        if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+            log_daemon_msg "Running DKMS auto installation service for kernel $kernel"
+        else
+	    echo "Running DKMS auto installation service for kernel $kernel"
+	fi
+        echo "" >>$output_loc
 
 	for filename in `ls "$dkms_tree"`; do
 	    if [ -d "$dkms_tree/$filename" ] && ! [ -h "$dkms_tree/$filename" ]; then
@@ -95,49 +106,80 @@ case "$1" in
 		    fi
 		done
 
+                if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+                    log_action_begin_msg " $module_in_tree ($version_in_tree)"
+                fi                    
+
 		# Based on what we know, either do it or not
 		if [ "$current_state" = "broken" ]; then
-                    echo "$module_in_tree ($version_in_tree): Unable to locate $dkms_tree/$module_in_tree/$version_in_tree/source/dkms.conf" > $output_loc
-                    echo -e "\tDKMS tree must be manually fixed." >$output_loc              
-                    continue      
+                    echo "$module_in_tree ($version_in_tree): Unable to locate $dkms_tree/$module_in_tree/$version_in_tree/source/dkms.conf" >>$output_loc
+                    echo -e "\tDKMS tree must be manually fixed." >>$output_loc
+                    if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+                        log_action_end_msg 1
+                    fi
+                    continue
 		elif [ -n "$already_installed" ]; then
-		    echo "$module_in_tree ($already_installed_version): Already installed on this kernel." >$output_loc
+		    echo "$module_in_tree ($already_installed_version): Already installed on this kernel." >>$output_loc
+                    if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+                        log_action_end_msg 0
+                    fi
 		elif [ -z "$do_autoinstall" ]; then
-		    echo "$module_in_tree ($version_in_tree): AUTOINSTALL not set in its dkms.conf." >$output_loc
+		    echo "$module_in_tree ($version_in_tree): AUTOINSTALL not set in its dkms.conf." >>$output_loc
+                    if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+                        log_action_end_msg 0
+                    fi
 		elif [ -n "$do_autoinstall" ] && [ "$version_count" -gt 1 ]; then
-		    echo "$module_in_tree: Multiple versions in DKMS. Unsure what to do. Resolve manually." >$output_loc
+		    echo "$module_in_tree: Multiple versions in DKMS. Unsure what to do. Resolve manually." >>$output_loc
+                    if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+                        log_action_end_msg 1
+                    fi
 		else
-		    echo "$module_in_tree ($version_in_tree): Installing module." >$output_loc
+		    echo "$module_in_tree ($version_in_tree): Installing module." >>$output_loc
 		    if [ "$current_state" != "built" ] && ! [ -e /lib/modules/$kernel/build/include ]; then
-			echo "  Kernel source for $kernel not installed.  Cannot install this module." >$output_loc
+			echo "  Kernel source for $kernel not installed.  Cannot install this module." >>$output_loc
 		    elif [ "$current_state" != "built" ] && [ -e /lib/modules/$kernel/build/include ]; then
 			return_status=""
 			if [ -z "$kernel_preparation_done" ]; then
-			    invoke_command "dkms build -m $module_in_tree -v $version_in_tree -k $kernel -a $arch -q --no-clean-kernel >$output_loc" "." background
+			    invoke_command "dkms build -m $module_in_tree -v $version_in_tree -k $kernel -a $arch -q --no-clean-kernel >>$output_loc" "." background
 			    return_status="$?"
 			    kernel_preparation_done="true"
 			else
-			    invoke_command "dkms build -m $module_in_tree -v $version_in_tree -k $kernel -a $arch --no-prepare-kernel --no-clean-kernel -q >$output_loc" "." background
+			    invoke_command "dkms build -m $module_in_tree -v $version_in_tree -k $kernel -a $arch --no-prepare-kernel --no-clean-kernel -q >>$output_loc" "." background
 			    return_status="$?"
 			fi
 			if [ "$return_status" -eq 0 ]; then
-			    invoke_command "dkms install -m $module_in_tree -v $version_in_tree -k $kernel -a $arch -q >$output_loc" "." background
+			    invoke_command "dkms install -m $module_in_tree -v $version_in_tree -k $kernel -a $arch -q >>$output_loc" "." background
+                            if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+                                log_action_end_msg 0
+                            else
+                                echo "Done"
+                            fi
 			else
-			    echo "  Build failed.  Installation skipped." >$output_loc
+			    echo "  Build failed.  Installation skipped." >>$output_loc
+                            if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+                                log_action_end_msg 1
+                            else
+                                echo " Failed."
+                            fi
 			fi
 		    else
-			invoke_command "dkms install -m $module_in_tree -v $version_in_tree -k $kernel -a $arch -q >$output_loc" "." background
+			invoke_command "dkms install -m $module_in_tree -v $version_in_tree -k $kernel -a $arch -q >>$output_loc" "." background
 			return_status=$?
 			if [ "$return_status" -eq 101 ]; then
-			    echo "  A newer module version than this already exists in this kernel." >$output_loc
-			    echo "  Skipping install... (you can manually install later with --force)" >$output_loc
+			    echo "  A newer module version than this already exists in this kernel." >>$output_loc
+			    echo "  Skipping install... (you can manually install later with --force)" >>$output_loc
 			elif [ "$return_status" -ne 0 ]; then
-			    echo "  Installation failed!" >$output_loc
+			    echo "  Installation failed!" >>$output_loc
 			fi
 		    fi
   		fi
 	    fi
 	done
+        if [ ! -z "$DEBIAN_STYLE_LOGGING" ]; then
+            log_end_msg 0
+        else
+            echo -n "."
+        fi
 	;;
   stop)
 	# ignore
