Clean up check_version_sanity.
Return early in check_version_sanity, and only run the find command once.

Returning early helps make the rest of the code easier to read, running
find once instead of twice helps speed things up (even if it should be cached
the second time)

Only ever call an external program once if we can help it, and use
bash parameter expansion instead of external programs for cleanup purposes.

diff --git a/dkms b/dkms
--- a/dkms
+++ b/dkms
@@ -613,6 +613,16 @@ read_conf()
 }
 
 
+get_module_verinfo(){
+    local vals=()
+    while read -a vals; do
+	case ${vals[0]} in
+	    version:) res[0]=${vals[1]}; res[2]=${vals[2]};;
+	    srcversion:) res[1]=${vals[1]};;
+	esac
+    done < <(modinfo $1)
+}
+
 check_version_sanity()
 {
     # $1 = kernel_version
@@ -620,83 +630,74 @@ check_version_sanity()
     # $3 = obs by kernel version
     # $4 = dest_module_name
 
-    local lib_tree="$install_tree/$1"
+    local lib_tree="$install_tree/$1" res=()
     echo $"Running module version sanity check."
-    local module_count=`find $lib_tree -name ${4}$module_suffix | wc -l | awk {'print $1'}`
-    if [ $module_count -gt 1 ]; then
-        echo $"Warning! Cannot do version sanity checking because multiple ${4}$module_suffix" >&2
+    local i=0
+    read -a kernels_module < <(find $lib_tree -name ${4}$module_suffix)
+    [[ $kernels_module ]] || return 0
+    if [[ ${kernels_module[1]} ]]; then
+	echo $"Warning! Cannot do version sanity checking because multiple ${4}$module_suffix" >&2
         echo $"modules were found in kernel $1." >&2
-    elif [ $module_count -eq 1 ]; then
-        local kernels_module=`find $lib_tree -name ${4}$module_suffix`
-        local kernels_ver_string=`modinfo $kernels_module | grep "^version:"`
-        local kernels_ver_value=`echo $kernels_ver_string | awk {'print $2'}`
-        local dkms_module="$dkms_tree/$module/$module_version/$1/$2/module/${4}$module_suffix"
-        local dkms_ver_string=`modinfo $dkms_module | grep "^version:"`
-        local dkms_ver_value=`echo $dkms_ver_string | awk {'print $2'}`
-
-        # there are 2 possible srcversion checksums
-        # one in the 'srcversion' tag alone (preferred)
-        # and one following the version field in the 'version' tag (deprecated)
-        local kernels_ver_checksum=`modinfo $kernels_module | awk '/^srcversion:/ {print $2}'`
-        local dkms_ver_checksum=`modinfo $dkms_module | awk '/^srcversion:/ {print $2}'`
-        if [ -z "$kernels_ver_checksum" -a -z "$dkms_ver_checksum" ]; then
-            kernels_ver_checksum=`echo $kernels_ver_string | awk {'print $3'}`
-            dkms_ver_checksum=`echo $dkms_ver_string | awk {'print $3'}`
-        fi
-
-        if [ -n "$kernels_ver_checksum" -a -n "$dkms_ver_checksum" -a \
-            "$kernels_ver_checksum" == "$dkms_ver_checksum" -a -z "$force" ]; then
-            echo $"" >&2
-            echo $"Good news! Module version $dkms_ver_value for ${4}$module_suffix" >&2
-            echo $"exactly matches what is already found in kernel $1." >&2
-            echo $"DKMS will not replace this module." >&2
-            echo $"You may override by specifying --force." >&2
-            return 1
-        fi
-
-        if [ -n "$kernels_ver_value" -a -n "$dkms_ver_value" ]; then
-            if [[ ! ( $(VER $dkms_ver_value) > \
-                      $(VER $kernels_ver_value) ) && -z "$force" ]]; then
-                echo $"" >&2
-                echo $"Error! Module version $dkms_ver_value for ${4}$module_suffix" >&2
-                echo $"is not newer than what is already found in kernel $1 ($kernels_ver_value)." >&2
-                echo $"You may override by specifying --force." >&2
-                return 1
-            fi
-        fi
-
-        local obs_upstream=`echo $3 | cut -d- -f 1`
-        local obs_local=`echo $3 | cut -d- -f 2`
-        local my_upstream=`echo $1 | cut -d- -f 1`
-        local my_local=`echo $1 | cut -d- -f 2`
-        local obsolete=0
-        if [ -n "$obs_upstream" -a -n "$my_upstream" ]; then
-            if [[ ( $(VER $obs_upstream) == $(VER $my_upstream) ) && -z "$force" ]]; then
+	return 0
+    fi
+    local dkms_module="$dkms_tree/$module/$module_version/$1/$2/module/${4}$module_suffix"
+    get_module_verinfo $kernels_module; kernels_info=("${res[@]}")
+    get_module_verinfo $dkms_module; dkms_info=("${res[@]}")
+    if [[ ! ${dkms_info[1]} && ${kernels_info[1]} ]]; then
+	# use obsolete checksum info
+	dkms_info[1]=${dkms_info[2]}
+	kernels_info[1]=${kernels_info[2]}
+    fi
+    
+    if [[ ${kernels_info[1]} && ${dkms_info[1]} && \
+        ${kernels_info[1]} = ${dkms_info[1]} && ! $force ]]; then
+        echo $"" >&2
+        echo $"Good news! Module version $dkms_info for ${4}$module_suffix" >&2
+        echo $"exactly matches what is already found in kernel $1." >&2
+        echo $"DKMS will not replace this module." >&2
+        echo $"You may override by specifying --force." >&2
+        return 1
+    fi
+    
+    if [[ $kernels_info && $dkms_info && \
+	! ( $(VER $dkms_info) > $(VER $kernels_info) ) && ! $force ]]; then
+        echo $"" >&2
+        echo $"Error! Module version $dkms_info for ${4}$module_suffix" >&2
+        echo $"is not newer than what is already found in kernel $1 ($kernels_info)." >&2
+        echo $"You may override by specifying --force." >&2
+        return 1
+    fi
+    
+    # magic split into array syntax saves trivial awk and cut calls.
+    local obs=(${3//-/ })
+    local my=(${1//-/ })
+    local obsolete=0
+    if [[ ${obs} && ${my} ]]; then
+        if [[ $(VER ${obs}) == $(VER ${my}) && ! $force ]]; then
             #they get obsoleted possibly in this kernel release
-                if [ -z "$obs_local" ]; then
+            if [[ ! ${obs[1]} ]]; then
                 #they were obsoleted in this upstream kernel
-                    obsolete=1
-                elif [[ ( $(VER $my_local) > $(VER $obs_local) ) ]]; then
+                obsolete=1
+            elif [[ $(VER ${my[1]}) > $(VER ${obs[1]}) ]]; then
                 #they were obsoleted in an earlier ABI bump of the kernel
-                    obsolete=1
-                elif [[ ( $(VER $my_local) = $(VER $obs_local) ) ]]; then
+                obsolete=1
+            elif [[ $(VER ${my[1]}) = $(VER ${obs[1]}) ]]; then
                 #they were obsoleted in this ABI bump of the kernel
-                    obsolete=1
-                fi
-            elif [[ ( $(VER $my_upstream) > $(VER $obs_upstream) ) && -z "$force" ]]; then
-            #they were obsoleted in an earlier kernel release
                 obsolete=1
             fi
+        elif [[ $(VER ${my}) > $(VER ${obs}) && ! $force ]]; then
+            #they were obsoleted in an earlier kernel release
+            obsolete=1
         fi
-
-        if [ "$obsolete" == 1 ]; then
-            echo $"" >&2
-            echo $"Module has been obsoleted due to being included" >&2
-            echo $"in kernel $3.  We will avoid installing" >&2
-            echo $"for future kernels above $3." >&2
-            echo $"You may override by specifying --force." >&2
-            return 1
-        fi
+    fi
+    
+    if ((obsolete == 1)); then
+        echo $"" >&2
+        echo $"Module has been obsoleted due to being included" >&2
+        echo $"in kernel $3.  We will avoid installing" >&2
+        echo $"for future kernels above $3." >&2
+        echo $"You may override by specifying --force." >&2
+        return 1
     fi
     return 0
 }
