import of v2.0.9.3

diff --git a/dkms b/dkms
--- a/dkms
+++ b/dkms
@@ -273,6 +273,7 @@ function read_conf ()
     POST_INSTALL=""
     POST_REMOVE=""
     PRE_BUILD=""
+    PRE_INSTALL=""
     BUILD_EXCLUSIVE_KERNEL=""
     BUILD_EXCLUSIVE_ARCH=""
     build_exclude=""
@@ -337,6 +338,7 @@ function read_conf ()
     post_install="$POST_INSTALL"
     post_remove="$POST_REMOVE"
     pre_build="$PRE_BUILD"
+    pre_install="$PRE_INSTALL"
 
     # Set module naming/location arrays
     local index=0
@@ -945,6 +947,18 @@ function install_module()
 
     # Check this version against what is already in the kernel
     check_version_sanity "${kernelver_array[0]}" "${arch_array[0]}"
+
+    # Run the pre_install script
+    if [ -n "$pre_install" ] && [ -x `echo "$dkms_tree/$module/$module_version/source/$pre_install" | sed 's/ .*//'` ]; then
+	echo $""
+	echo $"Running the pre_install script:"
+	$dkms_tree/$module/$module_version/source/$pre_install
+	if [ "$?" -ne 0 -a -z "$force" ]; then
+	    echo $"pre_install failed, aborting install." >&2
+	    echo $"You may override by specifying --force." >&2
+	    exit 101
+	fi
+    fi
 
     # Save the original_module if one exists, none have been saved before, and this is the first module for this kernel
     local lib_tree="$install_tree/${kernelver_array[0]}"
@@ -2576,7 +2590,7 @@ while [ $# -gt 0 ]; do
 	    exec >/dev/null 2>&1
 	    ;;
 	--version|-V)
-	    echo $"dkms: 2.0.9.2"
+	    echo $"dkms: 2.0.9.3"
 	    exit 0
 	    ;;
 	--no-prepare-kernel)
