add support for make_debian to include the actual files of the source in the deb rather than in a tarball.  the tarball will still be used to distribute binaries (optionally)

diff --git a/dkms b/dkms
--- a/dkms
+++ b/dkms
@@ -2799,7 +2799,7 @@ make_tarball()
 	cp -rf $dkms_tree/$module/$module_version/source/* $temp_dir_name/dkms_source_tree
     else
 	echo $""
-	echo $"Binaries only specified.  Creating special tarball structure to accomodate."
+	echo $"Creating special tarball structure to accomodate only binaries."
 	mkdir $temp_dir_name/dkms_binaries_only
 	echo "$module" > $temp_dir_name/dkms_binaries_only/PACKAGE_NAME
 	echo "$module_version" > $temp_dir_name/dkms_binaries_only/PACKAGE_VERSION
@@ -3019,9 +3019,7 @@ load_tarball()
     done
 
     # Create source symlink
-    if [ -h "$dkms_tree/$module/$module_version/source" ] && [ -z "$force" ]; then
-	echo $"Warning! $dkms_tree/$module/$module_version/source already exists.  Skipping..." >&2
-    else
+    if [ ! -h "$dkms_tree/$module/$module_version/source" ] || [ ! -z "$force" ]; then
 	echo $"Creating $dkms_tree/$module/$module_version/source symlink..."
 	rm -f "$dkms_tree/$module/$module_version/source"
 	ln -s "$source_tree/$module-$module_version" "$dkms_tree/$module/$module_version/source"
@@ -3334,25 +3332,10 @@ function make_debian()
         exit 5
     fi
 
-    #test for binary or source modules
-    local mktarball_line
-    if [ -n "$source_only" ]; then
-        mktarball_line="--source-only"
-    else
-        local i=0
-        echo $""
-        while [ $i -lt ${#kernelver_array[@]} ]; do
-            if ! [ -d "$dkms_tree/$module/$module_version/${kernelver_array[$i]}/${arch_array[$i]}" ]; then
-                echo $"" >&2
-                echo $"You do not seem to have $module $module_version built for" >&2
-                echo $"${kernelver_array[$i]} (${arch_array[$i]}).  All modules must be in" >&2
-                echo $"the built state before you can use mkdeb." >&2
-                exit 5
-            fi
-            echo $"Marking ${kernelver_array[$i]} (${arch_array[$i]}) for deb..."
-            mktarball_line="-k ${kernelver_array[$i]} -a ${arch_array[$i]} $mktarball_line"
-            i=$(($i + 1))
-        done
+    if [ -n "$binaries_only" ]; then
+        echo $"" >&2
+        echo $"Error! Debian archives can not be made in binaries only mode." >&2
+        exit 13
     fi
 
     #prepare build directory and copy template
@@ -3372,16 +3355,22 @@ function make_debian()
         invoke_command "cp '$PREFIX/usr/lib/dkms/common.postinst' '$temp_dir_debian'" "copying legacy postinstall template"
     fi
 
-    #create tar.gz that lives in DKMS deb
-    archive_location="$module-$module_version.dkms.tar.gz"
-    invoke_command "make_tarball -m $module -v $version $mktarball_line" "gathering sources"
-    if [ -f $dkms_tree/$module/$module_version/tarball/$archive_location ]; then
-        invoke_command "cp '$dkms_tree/$module/$module_version/tarball/$archive_location' '$temp_dir_debian'" "Copying DKMS tarball into DKMS tree"
-    else
-        echo $"" >&2
-        echo $"Error! Unable to find created tarball." >&2
-        exit 12
+    #Only if we are shipping binary modules, make a .tgz for the deb
+    local archive_location="$module-$module_version.dkms.tar.gz"
+    if [ ! -n "$source_only" ]; then
+        binaries_only="binaries-only"
+        invoke_command "make_tarball" "Gathering binaries"
+        if [ -f $dkms_tree/$module/$module_version/tarball/$archive_location ]; then
+            invoke_command "cp '$dkms_tree/$module/$module_version/tarball/$archive_location' '$temp_dir_debian'" "Copying DKMS tarball into DKMS tree"
+        else
+            echo $"" >&2
+            echo $"Error! Unable to find created tarball." >&2
+            exit 12
+        fi
     fi
+
+    #Copy in the source tree
+    invoke_command "cp -Lpr '$dkms_tree/$module/$module_version/source' '$temp_dir_debian/$module-$module_version'" "Copying source tree"
 
     #calculate destination directory
     deb_basedir=$dkms_tree/$module/$module_version/${create_type}
