debian/postinst: check for /etc/kernel-img.conf before modifying

diff --git a/pkg/debian/postinst b/pkg/debian/postinst
--- a/pkg/debian/postinst
+++ b/pkg/debian/postinst
@@ -8,16 +8,18 @@ case "$1" in
     kconf="/etc/kernel-img.conf"
     hookline="header_postinst_hook = /etc/kernel/postinst.d/dkms"
 
-    if [ $(grep -c header_postinst_hook "$kconf") -eq 0 ]; then
-        echo "$hookline" >> "$kconf"
-    elif [ $(grep -c "$hookline" "$kconf") -eq 0 ]; then
-	# we're already there, nothing to do
-	:
-    else
-        echo "WARNING: COULD NOT INSTALL header_postinst_hook!"
-        echo "Reason: There was already a hook inside kernel-img.conf"
-        echo "Installation will continue, however, kernel updates"
-        echo "may not properly automatically install new modules."
+    if [ -e $kconf ]; then
+	if ! grep -c ^header_postinst_hook "$kconf" ; then
+	    echo "$hookline" >> "$kconf"
+	elif grep -c "$hookline" "$kconf" ; then
+	    # we're already there, nothing to do
+	    :
+	else
+	    echo "WARNING: COULD NOT INSTALL header_postinst_hook!"
+	    echo "Reason: There was already a hook inside kernel-img.conf"
+	    echo "Installation will continue, however, kernel updates"
+	    echo "may not properly automatically install new modules."
+	fi
     fi
 
     ;;
