Merge with debian's dh_dkms improvements

diff --git a/debian/scripts/postinst-dkms b/debian/scripts/postinst-dkms
--- a/debian/scripts/postinst-dkms
+++ b/debian/scripts/postinst-dkms
@@ -3,23 +3,25 @@
 
 DKMS_NAME=#MODULE_NAME#
 DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
-DKMS_CVERSION=$(dpkg-query -W -f='${Version}' $DKMS_PACKAGE_NAME | awk -F "-" '{print $1}' | cut -d\: -f2)
+DKMS_VERSION=#MODULE_VERSION#
+
+postinst_found=0
 
 case "$1" in
 	configure)
 		for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
 			if [ -f $DKMS_POSTINST ]; then
-				$DKMS_POSTINST $DKMS_NAME $DKMS_CVERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
-				if [ "$?" -ne 0 ]; then
-					exit $?
-				fi
+				$DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
+				postinst_found=1
+				break
 			fi
-			echo "WARNING: $DKMS_POSTINST does not exist."
 		done
-		echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
-		echo "built with legacy DKMS support."
-		echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
-		echo "support or upgrade DKMS to a more current version."
-		exit 1
+		if [ "$postinst_found" -eq 0 ]; then
+			echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
+			echo "built with legacy DKMS support."
+			echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
+			echo "support or upgrade DKMS to a more current version."
+			exit 1
+		fi
 	;;
 esac
