CI: fetch the kernel name of disk
Swap the distro specific and somewhat hacky parsing of the kernel
version. Just pick the one off {/usr,}/lib/modules and error out if
there is more than one.

Signed-off-by: Emil Velikov <emil.l.velikov@gmail.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -45,37 +45,27 @@ jobs:
       if: matrix.distro.name == 'almalinux'
       run: |
         yum install -y diffutils elfutils-libelf-devel gcc kernel kernel-devel make openssl
-        KERNEL_VER="$(LANG=C rpm -qi kernel-devel | sed -n 's/^Source RPM *: kernel-\(.*\).src.rpm$/\1.x86_64/p' | tail -n 1)"
-        echo "KERNEL_VER=${KERNEL_VER}" >> "$GITHUB_ENV"
 
     - name: Install Alpine dependencies
       if: matrix.distro.name == 'alpine'
       run: |
         apk --no-cache --update add bash gcc linux${{ matrix.distro.variant }} linux${{ matrix.distro.variant }}-dev make openssl coreutils
-        KERNEL_VER="$(apk info --contents "linux${{ matrix.distro.variant }}-dev" | sed -n 's:^lib/modules/\([^/][^/]*\)/.*:\1:p' | head -n 1)"
-        echo "KERNEL_VER=${KERNEL_VER}" >> "$GITHUB_ENV"
 
     - name: Install Arch Linux dependencies
       if: matrix.distro.name == 'archlinux'
       run: |
         pacman -Syu --noconfirm diffutils gcc make linux${{ matrix.distro.variant }}-headers openssl
-        KERNEL_VER="$(pacman -Qql "linux${{ matrix.distro.variant }}-headers" | sed -n 's:^/usr/lib/modules/\([^/]\+\)/.*:\1:p' | head -n 1)"
-        echo "KERNEL_VER=${KERNEL_VER}" >> "$GITHUB_ENV"
 
     - name: Install CentOS dependencies
       if: contains(matrix.distro.name, 'centos')
       run: |
         yum install -y diffutils elfutils-libelf-devel gcc kernel kernel-devel make openssl
-        KERNEL_VER="$(LANG=C rpm -qi kernel-devel | sed -n 's/^Source RPM *: kernel-\(.*\).src.rpm$/\1.x86_64/p' | tail -n 1)"
-        echo "KERNEL_VER=${KERNEL_VER}" >> "$GITHUB_ENV"
 
     - name: Install Debian dependencies
       if: matrix.distro.name == 'debian'
       run: |
         apt-get update -q
         apt-get install -qy make linux-headers-amd64 linux-image-amd64 openssl
-        KERNEL_VER="$(LANG=C dpkg --status linux-headers-amd64 | sed -n 's/^Depends: linux-headers-\(\S\+\)\( .*\)\?/\1/p' | head -n 1)"
-        echo "KERNEL_VER=${KERNEL_VER}" >> "$GITHUB_ENV"
 
     - name: Install Gentoo Linux dependencies
       if: matrix.distro.name == 'gentoo/stage3'
@@ -83,28 +73,38 @@ jobs:
         echo -e "sys-kernel/gentoo-kernel-bin\nvirtual/dist-kernel" >> /etc/portage/package.accept_keywords/latest-kernel
         emerge --sync
         emerge --noreplace -j$(nproc) -l$(nproc) gentoo-kernel-bin
-        dist_kernel_ver="$(emerge --search gentoo-kernel-bin | sed -n 's/^[[:space:]]*Latest version installed: \([0-9.]\)/\1/p' | head -n 1)"
-        KERNEL_VER="${dist_kernel_ver%-r*}-gentoo-dist"
-        echo "KERNEL_VER=${KERNEL_VER}" >> "$GITHUB_ENV"
 
     - name: Install Ubuntu dependencies
       if: matrix.distro.name == 'ubuntu'
       run: |
         apt-get update -q
         apt-get install -qy gcc make linux-headers-generic linux-image-generic openssl shim-signed
-        KERNEL_VER="$(LANG=C dpkg --status linux-headers-generic | sed -n 's/^Depends: linux-headers-\(\S\+\)\( .*\)\?/\1/p' | head -n 1)"
-        echo "KERNEL_VER=${KERNEL_VER}" >> "$GITHUB_ENV"
 
     - name: Install dkms
       run: make install
 
     - name: Run tests
       run: |
+        for moddir in /usr/lib/modules/ /lib/modules/; do
+            if [ -e "$moddir" ]; then
+                kernels=$(find "$moddir" -maxdepth 1 -type d -exec basename {} \;)
+                break
+            fi
+        done
+
+        # There should be two entries - "modules" and the kernel we installed
+        if [ $(echo "${kernels}" | wc -l) -ne 2 ]; then
+            echo >&2 "Error: invalid number of kernels installed"
+        fi
+
+        KERNEL_VER=$(echo "${kernels}" | tail -n1)
         if [ -z "${KERNEL_VER}" ] ; then
             echo >&2 "Error: no kernel package found"
             exit 1
         fi
-        echo "Found packaged kernel ${KERNEL_VER}"
+
+        echo "Found kernel ${KERNEL_VER}"
+        export KERNEL_VER
         if [ "${{ matrix.distro.name }}" = alpine ] && [ "${{ matrix.distro.variant }}" = "-lts" ]; then
             ./run_test.sh --no-signing-tool
         else
